apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-z8qj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-z8qj
    app.kubernetes.io/part-of: ci10t-777-0060-app
  name: devfile-sample-z8qj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-z8qj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-z8qj
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0060-tenant/ci10t-777-0060-app/devfile-sample-z8qj@sha256:3ae1c07db594fefae06fafcc2d4c6b70951c91578a3e9f3e182b9dddec41fc50
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
